name: Generate Snake Game

on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Generate snake.svg
        run: |
          pip install pygithub
          python .github/scripts/generate_snake.py
          
      - name: Push snake.svg to output branch
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout --orphan output || git checkout output
          git reset --hard
          git add snake.svg
          git commit -m "Update snake animation"
          git push origin output --force